### PR TITLE
Try executing Python instead of the Python "script"

### PR DESCRIPTION
**Pull request by Myoldmopar**

### CODE REVIEW

**Comment by mitchute** [comment]
FYI: Same issue over on the wall_temp example.

**Comment by Myoldmopar** [comment]
Of course...

**Comment by Myoldmopar** [comment]
That should take care of that one too, @mitchute

**Comment by mitchute** [comment]
Yep. Looks good over here.

**Comment by Myoldmopar** [comment]
Merging; thanks!

**Pull request merged**
